services:
  db:
    image: rethinkdb
    container_name: rethinkdb
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
      - 28015:28015
      # - ${APP_CLIENT_PORT}:28015
      # - ${APP_CLUSTER_PORT}:29015
    command:
      - /bin/bash
      - -c
      - |
        rethinkdb create --initial-password  ${DB_PASSWORD}
        rethinkdb --bind all
    volumes:
      - ./rethinkdb/data:/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - .env

    volumes:
      - ./backend:/python-docker
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      JWT_SECRET_KEY: "3850-0252-0571-4373"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80
