services:
  db:
    image: rethinkdb
    container_name: rethinkdb
    restart: always
    env_file:
      - .env
    #[DOCKER]
    network_mode: "host"
    ports:
      - 8080:8080
      - 28015:28015
    command:
      - /bin/bash
      - -c
      - |
        rethinkdb create --initial-password  ${DB_PASSWORD}
        rethinkdb --bind all --bind-http 127.0.0.1
    volumes:
      - ./rethinkdb/data:/data

  backend:
    build: ./backend
    ####################
    # [LOCAL]
    network_mode: "host"
    # [ DOCKER ]
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - .env

    volumes:
      - ./backend:/python-docker
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 80:80
